add_newline = false
continuation_prompt = "[▸▹ ](dimmed fg:gold)"

format = """
[░▒▓](fg:highlight-med)\
$os\
$username\
[ ](fg:highlight-med)\
$directory\
$git_branch\
$git_status\
$fill\
$netns\
\n$cmd_duration$sudo$character"""

right_format = """
$package\
$nodejs\
$php\
$rust\
$c\
$cpp\
$cmake\
"""

palette = "rose-pine-moon"

[palettes.rose-pine-moon]
base = '#232136'
surface = '#2a273f'
overlay = '#393552'
muted = '#6e6a86'
text = '#e0def4'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ea9a97'
pine = '#3e8fb0'
foam = '#9ccfd8'
iris = '#c4a7e7'
highlight-med = '#44415a'

[fill]
symbol = ' '

[os]
format = "[ $symbol]($style)"
style = "bg:highlight-med bold fg:iris"
disabled = false

[username]
format = '[$user]($style)'
style_user = "bg:highlight-med fg:iris"
style_root = ""
show_always = true
disabled = false

[directory]
format = '[on](bold fg:muted)[$read_only]($read_only_style)[$symbol $path]($style)'
style = "italic fg:text"
home_symbol = "󱂵 "
truncation_symbol = "󰉋 "
read_only = "󰉐 "
truncation_length = 3
use_os_path_sep = true
repo_root_style = 'italic fg:text'
repo_root_format = '[$read_only]($read_only_style)[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)'

[netns]
format = '[$symbol $name]($style)'
style = 'bold fg:pine'
symbol = '󰖩 '

[cmd_duration]
format = "[ ◄ $duration ](italic fg:gold)"

[sudo]
format = "[ $symbol]($style)"
style = 'bold fg:rose'
symbol = ''
disabled = false

[character]
format = " $symbol "
success_symbol = '[_\$](italic fg:pine)'
error_symbol = '[_!](italic fg:love)'
vimcmd_symbol = "[_❯ ](italic dimmed fg:foam)"


[git_branch]
format = " — $symbol [$branch(:$remote_branch)]($style) "
style = "italic bright-green"
symbol = "[](bold italic bright-green)"
truncation_symbol = "⋯"
truncation_length = 11
ignore_branches = []
only_attached = true

[git_metrics]
format = '([▴$added]($added_style))([▿$deleted]($deleted_style))'
added_style = 'italic dimmed green'
deleted_style = 'italic dimmed red'
ignore_submodules = true
disabled = false

[git_status]
format = '[\[$ahead_behind$staged$modified$untracked$renamed$deleted$conflicted$stashed\]]($style)'
style = "bold italic bright-blue"
ahead = "[ (bold white)](italic green)"
behind = "[ (bold white)│](italic red)"
staged = "[ [$count](bold white)│](italic bright-cyan)"
modified = "[ ](italic yellow)"
untracked = "[󰍑 ](italic bright-yellow)"
renamed = "[ ](italic bright-blue)"
deleted = "[󰆴](italic red)"
conflicted = "[ ](italic bright-magenta)"
diverged = "[◇ ▴┤[${ahead_count}](regular white)│▿┤[${behind_count}](regular white)│](italic bright-magenta)"
stashed = "[◃◈](italic white)"

[package]
format = "[pkg](italic dimmed) [$symbol$version]($style)"
version_format = "v${raw}"
symbol = "󰏗 "
style = "dimmed yellow bold"
display_private = true

[nodejs]
format = " [via](none) [node](italic bright-green) [ ($version(:$engines_version))](bold bright-green) "
version_format = "v${raw}"
detect_files = ["package-lock.json", "yarn.lock", "package.json"]
detect_folders = ["node_modules"]
detect_extensions = []

[php]
format = " [via](none) [php](italic dimmed purple) [ ($version)](bold dimmed purple) "
version_format = "v${raw}"
detect_files = ["composer.json"]
detect_folders = ["node_modules"]
detect_extensions = ["php"]

[rust]
format = " [via](none) [rust](italic $style) [ ($version)]($style) "
version_format = "v${raw}"
style = "bold red"
detect_files = ["Cargo.toml"]
detect_folders = []
detect_extensions = ["rs"]

[c]
format = " [via](none) [c](italic $style) [ ($version(-$name))]($style) "
version_format = "v${raw}"
style = "bold 149"
detect_files = []
detect_folders = []
detect_extensions = ["c", "h"]
commands = [ [ 'cc', '--version' ], [ 'gcc', '--version' ], [ 'clang', '--version' ] ]

[cpp]
format = " [via](none) [cpp](italic $style) [ ($version(-$name))]($style) "
version_format = "v${raw}"
style = "bold 149"
detect_files = []
detect_folders = []
detect_extensions = ['cpp', 'cc', 'cxx', 'c++', 'hpp', 'hh', 'hxx', 'h++', 'tcc']
commands = [ [ 'c++', '--version' ], [ 'g++', '--version' ], [ 'clang++', '--version' ] ]

[cmake]
format = "[with](none) [CMake](italic $style) [ ($version)]($style) "
version_format = "v${raw}"
style = "bold dimmed red"
detect_files = ['CMakeLists.txt', 'CMakeCache.txt']
detect_folders = []
detect_extensions = []




[os.symbols]
Arch = "󰣇 "
Artix = " "
CachyOS = " "
EndeavourOS = " "
Garuda = " "
Linux = " "
Manjaro = "󱘊 "